# Na aula anterior...

Por que o algoritmo se chama **Naive** Bayes?

Como escolhemos a nossa resposta a partir do Naive Bayes?

Por que as probabilidades das categorias eram diferentes quando calculadas manualmente e calculadas pelo modelo sklearn?

Por que existem vários tipos de Naive Bayes no sklearn?

Vantagem do Naive Bayes?

# Lembretes

- Exercício no Class! - 11/set
- Projeto no Class! - 11/set
- Última aula, então avaliação do módulo

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
modelo = DecisionTreeClassifier()

In [ ]:
class Pessoa:
    
    def __init__(self, nome):
        self.nome = nome
        
    def saudacao(self):
        return f'oi, meu nome é {self.nome}'

In [ ]:
p1 = Pessoa(nome = 'Rychard')
p2 = Pessoa(nome = 'Bruno')
p3 = Pessoa(nome = 'Telson')

In [ ]:
p1.saudacao()

'oi, meu nome é Rychard'

In [ ]:
from sklearn.tree import DecisionTreeClassifier

class RandomForest:

    ## TODO se achar necessário, adicionar novos parâmetros no construtor
    def __init__(self, n_arvores, modelo):
        self.n_arvores = n_arvores
        self.modelo = modelo

    def __repr__(self):
        return f'Random Classifier com {self.n_arvores} modelos do tipo {str(self.modelo)}'

    # TODO ajustar método fit
    def fit(self, x, y):

        self.modelo.fit(x, y)
        return

    # TODO criar método predict
    def predict(self, x):

        return

# Hoje!

## Pipeline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer, KNNImputer

from sklearn.neighbors import KNeighborsClassifier

In [ ]:
df = pd.read_csv('dados/titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
var_expl = ['Sex', 'Embarked']
var_resp = 'Survived'

df.dropna(subset = var_expl, inplace = True)

df_treino, df_teste = train_test_split(df, test_size = 0.2, random_state = 1)

x_treino = df_treino[var_expl].copy()
x_teste = df_teste[var_expl].copy()

y_treino = df_treino[var_resp].copy()
y_teste = df_teste[var_resp].copy()

In [ ]:
x_treino.head()

Sex Embarked
121  male        S
687  male        S
790  male        Q
837  male        S
659  male        C

### Sem pipeline

In [ ]:
oe = OrdinalEncoder()
oe.fit(x_treino)
x_treino = oe.transform(x_treino)
x_teste = oe.transform(x_teste)

minmax = MinMaxScaler()
minmax.fit(x_treino)
x_treino = minmax.transform(x_treino)
x_teste = minmax.transform(x_teste)

In [ ]:
x_treino

array([[1. , 1. ],
       [1. , 1. ],
       [1. , 0.5],
       ...,
       [1. , 0. ],
       [1. , 1. ],
       [1. , 1. ]])

In [ ]:
modelo = KNeighborsClassifier()
modelo.fit(x_treino, y_treino)

y_teste_pred = modelo.predict_proba(x_teste)[:, 1]

In [ ]:
y_teste_pred

array([0.8, 0.8, 0.2, 0.8, 0.2, 0.8, 0.8, 0.8, 0.2, 0.8, 0.2, 0.6, 0.2,
       0.8, 0.2, 0.8, 0.2, 0.8, 0.8, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.8,
       0.6, 0.2, 0.2, 0.8, 0.8, 0.2, 0.8, 0.2, 0.2, 0.8, 0.2, 0.2, 0.8,
       0.2, 0.8, 0.2, 0.2, 0.2, 0.2, 0.8, 0.8, 0.2, 0.8, 0.2, 0.2, 0.2,
       0.2, 0.8, 0.2, 0.8, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.8, 0.2, 0.2, 0.2, 0.8, 0.2, 0.8, 0.8, 0.2, 0.8, 0.8, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.6, 0.6, 0.2, 0.2, 0.8, 0.2, 0.2, 0.8, 0.2,
       0.8, 0.2, 0.2, 0.6, 0.2, 0.8, 0.8, 0.6, 0.8, 0.2, 0.8, 0.2, 0.2,
       0.2, 0.2, 0.6, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.6, 0.8, 0.6, 0.2,
       0.8, 0.6, 0.2, 0.2, 0.6, 0.8, 0.2, 0.8, 0.2, 0.2, 0.2, 0.2, 0.8,
       0.8, 0.2, 0.2, 0.2, 0.8, 0.8, 0.2, 0.2, 0.2, 0.2, 0.2, 0.8, 0.2,
       0.8, 0.2, 0.2, 0.6, 0.6, 0.8, 0.2, 0.2, 0.2, 0.6, 0.2, 0.2, 0.8,
       0.2, 0.8, 0.2, 0.2, 0.2, 0.2, 0.8, 0.2, 0.2, 0.2, 0.6, 0.6, 0.2,
       0.8, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2])

In [ ]:
roc_auc_score(y_teste, y_teste_pred)

0.8114155251141552

### Usando pipeline

In [1]:
from sklearn.pipeline import Pipeline

In [ ]:
var_expl = ['Sex', 'Embarked']
var_resp = 'Survived'

df.dropna(subset = var_expl, inplace = True)

df_treino, df_teste = train_test_split(df, test_size = 0.2, random_state = 1)

x_treino = df_treino[var_expl].copy()
x_teste = df_teste[var_expl].copy()

y_treino = df_treino[var_resp].copy()
y_teste = df_teste[var_resp].copy()

In [ ]:
pipe = Pipeline(steps = [
    ('passo_1', OrdinalEncoder()),
    ('passo_2', MinMaxScaler()),
    ('passo_3', KNeighborsClassifier()) 
])

In [ ]:
pipe.fit(x_treino, y_treino)

Pipeline(steps=[('passo_1', OrdinalEncoder()), ('passo_2', MinMaxScaler()),
                ('passo_3', KNeighborsClassifier())])

In [ ]:
y_pred_teste = pipe.predict_proba(x_teste)[:, 1]

In [ ]:
roc_auc_score(y_teste, y_teste_pred)

0.8114155251141552

In [62]:
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

**Exercício**: Contruir uma pipeline para fazer previsão dentro do iris, com modelo KNN e K = 10. Será necessário transformar os dados, utilizem o StandardScaler.

In [38]:
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data=data.data, columns=["sepal_len", "sepal_wid", "petal_len", "petal_wid"])
df['target'] = pd.Series(data.target)

df = df[df["target"] != 1]
df.head()

sepal_len  sepal_wid  petal_len  petal_wid  target
0        5.1        3.5        1.4        0.2       0
1        4.9        3.0        1.4        0.2       0
2        4.7        3.2        1.3        0.2       0
3        4.6        3.1        1.5        0.2       0
4        5.0        3.6        1.4        0.2       0

In [39]:
df['target'].value_counts()

0    50
2    50
Name: target, dtype: int64

In [48]:
# Separando os dados entre treino e teste
X_train, X_test, y_train, y_test = train_test_split(df.drop("target", axis=1),
                                                    df["target"],
                                                    test_size = 0.3,
                                                    random_state = 2)

In [60]:
pipe = Pipeline(steps = [
    ('passo_1', StandardScaler()),
    ('passo_2', KNeighborsClassifier())
])

In [68]:
params = {'passo_2__n_neighbors': np.arange(1,20)}

gscv = GridSearchCV(
    estimator = pipe,
    param_grid = params,
    refit=True,
    scoring = "accuracy",
    cv = 5
)

In [69]:
#pipe.fit(X_train, y_train)
gscv.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('passo_1', StandardScaler()),
                                       ('passo_2', KNeighborsClassifier())]),
             param_grid={'passo_2__n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])},
             scoring='accuracy')

In [70]:
gscv.best_params_

{'passo_2__n_neighbors': 1}

In [72]:
#y_pred_teste = pipe.predict_proba(X_test)[:, 1]
y_pred_teste = gscv.predict_proba(X_test)[:, 1]


In [73]:
y_pred_teste

array([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1.])

In [74]:
y_test

133    2
30     0
106    2
24     0
16     0
23     0
2      0
27     0
28     0
13     0
149    2
142    2
126    2
14     0
0      0
21     0
3      0
29     0
111    2
129    2
35     0
11     0
134    2
44     0
123    2
5      0
25     0
127    2
124    2
112    2
Name: target, dtype: int64

In [75]:
roc_auc_score(y_test, y_pred_teste)

1.0

## Otimização de Hiperparâmetros

Nesse ponto do curso já vimos diversos tipos de modelos preditivos. Alguns são mais simples e possuem pouca variabilidade dentro dele, como a Regressão Logística e o Naive Bayes; outros possuem um nível de complexidade um pouco maior no que tange aos comportamentos que esses algoritmos podem ter ao modificar configurações intrísecas a eles, como o KNN e as Árvores de Decisão. Para o primeiro, precisamos definir um K e uso de pesos; para o segundo, precisamos definir profundidade máxima, quantidade mínima de exemplos por folha, quantidade mínima de exemplos por quebra, pesos das classes, entre outros diversos hiperparâmetros. A definição desses hiperparâmetros pode alterar completamente o comportamento de um modelo, sendo então uma etapa essencial para modelagem. Dessa forma, é importante descobrir quais são os hiperparâmetros que criarão o melhor modelo para o cenário em questão, qual são os "números mágicos" que otimizarão o aprendizado do meu. Para um ou até dois parâmetros esse processo pode ser feito facilmente "na mão". Porém, à medida que a quantidade de hiperparâmetros aumenta, a quantidade de testes que temos que fazer aumentará *exponencialmente* e será bem útil fazer uso de algumas técnicas conhecidas.

### Diferenças entre Hiperparâmetro e Parâmetro

As nomenclaturas podem parecer um pouco confusas a primeira vista, mas são perceptíveis ao enxergar com mais atenção. Um parâmetro de um modelo é algo que será ajustado com no processo de *treinamento* dele. Como exemplo, podem ser citados os coeficientes da equação em uma Regressão Linear ou Logística ou as regras criadas pela Árvore de Decisão. Já um hiperparâmetro é uma configuração pré-definida de como o modelo se ajustará aos dados, definindo características construtivas do modelo.

### Grid Search

Talvez a primeira coisa que qualquer pessoa pense ao se deparar com esse problema é criar listas de parâmetros e testar todas as combinações possíveis. Logo, ao tentar otimizar 2 hiperparâmetros com três possibilidades em cada, testaremos então $3 \times 3 = 9$ modelos. O modelo que tiver melhor desempenho, será o escolhido.

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/14f61637-c80b-4ec3-8a1f-0c6e547ecb8d.png" style="height: 250px"/>

### Random Search

Funciona de forma muito similar ao Grid Search, criando um grid de parâmetros a serem testados. Porém, com a diferença de que a seleção dos valores escolhidos para teste é *aleatória* dado um conjunto de possibilidades. Ao invés de testar todos com todos, essa metodologia escolhe um valor ao acaso a partir de um conjunto pré-determinado. Mas uma escolha aleatória trás ganho?

Sim! [Alguns pesquisadores](https://s3-sa-east-1.amazonaws.com/lcpi/879e38fe-51f5-4f0e-abf1-339de202611b.pdf) perceberam que o Grid Search trás um problema na otimização dos valores: vamos supor que estamos testando os hiperparâmetros W, X, Y e Z, sendo $w$, $x$, $y$ e $z$ a quantidade de valores que cada hiperparâmetro receberá. Porém, modificar o W, por exemplo, trará uma variação desprezível no resultado do nosso modelo. Mas mesmo assim, por estar especificada no Grid Search, essa metodologia irá testar $ w \times x \times y \times z$, o que pode ser um desperdício. 

Além disso, ao especificar pontos estamos colocando um viés e pode ser que acabemos por não explorar espaços com máximos locais.

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/ccb2c843-3e26-4f56-bca5-e380d6964751.png" style="height: 250px"/>
